### ISSUE TITLE
Next release checklist

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#370]
- [x] - Fix gradle/pom generation license declaration for non-ASF licensed modules https://github.com/chrisdoyle/gradle-fury/issues/22
- [x] - Fix issues with name/description/developers in generated pom files
- [x] - GPG signatures on release version before publishing
- [X] - Gather release notes - posted to new wiki page
- [x] - Tag and publish to nexus
- [x] - Update playstore app
- [x] - Update wiki
- [x] - Upload distro package to github
- [x] - update readme.md

**Comment by k3b** [comment]
* create a 5.3-SNAPSHOT release so other lib-users can test it with their non-local osmdroid-dependency 
   * (on https://oss.sonatype.org/content/groups/public/org/osmdroid/osmdroid-android/)

**Comment by spyhunter99** [comment]
Can you perform the same task by running "gradlew install" which will
publish everything to your local maven cache

**Comment by MKergall** [comment]
When (very roughly) do you think the 5.3 will be officially released?

**Comment by neilboyd** [comment]
I'm trying to do it now but struggling a bit. It's the first time I've done it with gradle. I should have it done this week.

**Comment by k3b** [comment]
@spyhunter99: 

do you plan to finish #379 and #381  before releasing 5.3?

if you wait until tue 2016-08-30 i can use the weekend to have a deeper look at  #381 subtask 

* "is it possible to eleminate `net.sf.kxml:kxml` from `mapsforge`"

**Comment by spyhunter99** [comment]
Regarding mapsforge, there's not much I can do about it. They use it for
reading xml files or something. It's their dependency not ours

**Comment by atoone** [comment]
With the next release, can you validate that existing Tile Sources are working correctly? I'm aware that MapQuest has changed its API, but I'm also getting odd results with the thirdparty BingMapTileSource - it appears to be showing tiles from Australia for UK lat/longs.

**Comment by spyhunter99** [comment]
@k3b i just pushed proguard files or osmdroid-android and for the sample map app. I'm not doing the google wrapper or forge stuff right now.

i think the api clean up will need to wait for another day. the release is already large

**Comment by k3b** [comment]
i keep on investigating mapsforge. but with low priority.
currently we should keep net.sf.kxml:kxml although my currentbuild seems to run without it

**Comment by spyhunter99** [comment]
just heard from @neilboyd that the issues publishing to central have been resolved. Should have the released pushed out soon

**Comment by k3b** [comment]
@spyhunter99 thanks to the osmdroid team for the 5.4 new release.

* [v] upload to mavencentral: version 5.4 available 
  * see http://search.maven.org/#search%7Cga%7C1%7C%22org.osmdroid%22 
* [?] upload to jcenter: not complete (yet).
  * see https://bintray.com/search?query=osmdroid 
  * i.e. osmdroid-android has no javaodoc; 
  * not all packages available: i.e. osmdroid-mapsforge-5.4 is missing

**Comment by spyhunter99** [comment]
the javadocs are there. since it's an android flavor, there's a release and
debug variants for the library. It's there. Bintray's website is all sorts
of inaccurate. It amazes me that people actually use it.

**Comment by spyhunter99** [comment]
@k3b and thanks by the way. I can't tell you how many countless hours was spent trying to get gradle to so something basic.
